spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/web-chat'
    username: 'arkham'
    password: 'secret'
    driver-class-name: 'org.mariadb.jdbc.Driver'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MariaDBDialect'
