spring:
  datasource:
    url: 'jdbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/web-chat'
    username: '${DATABASE_USER}'
    password: '${DATABASE_PASSWORD}'
    driver-class-name: 'org.mariadb.jdbc.Driver'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'validate'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MariaDBDialect'
